# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{fast_trie}
  s.version = "0.3.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tyler McMullen"]
  s.date = %q{2009-11-23}
  s.description = %q{Ruby Trie based on libdatrie.}
  s.email = %q{tyler@scribd.com}
  s.extensions = ["ext/trie/extconf.rb"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.textile"
  ]
  s.files = [
    "README.textile",
     "VERSION.yml",
     "ext/trie/Makefile",
     "ext/trie/darray.c",
     "ext/trie/darray.h",
     "ext/trie/extconf.rb",
     "ext/trie/fileutils.c",
     "ext/trie/fileutils.h",
     "ext/trie/tail.c",
     "ext/trie/tail.h",
     "ext/trie/trie-private.c",
     "ext/trie/trie-private.h",
     "ext/trie/trie.c",
     "ext/trie/trie.h",
     "ext/trie/triedefs.h",
     "ext/trie/typedefs.h",
     "lib/trie.rb",
     "spec/trie_spec.rb"
  ]
  s.homepage = %q{http://github.com/tyler/trie}
  s.rdoc_options = ["--title", "Trie", "--line-numbers", "--op", "rdoc", "--main", "ext/trie/trie.c", "README"]
  s.require_paths = ["ext", "lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Ruby Trie based on libdatrie.}
  s.test_files = [
    "spec/trie_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

